version: '3.1'

services:

  cms:
    image: ghost:3-alpine
    restart: always
    depends_on:
      - db
    volumes:
      - ./data/ghost:/var/lib/ghost/content
    ports:
      - 80:2368
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: password
      database__connection__database: ghost
      url: http://localhost

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./data/database:/var/lib/mysql
    ports:
      - 3306:3306  
    environment:
      MYSQL_ROOT_PASSWORD: password