version: '3.1'

services:

  server:
    image: ghost:4.1
    depends_on:
      - db
    ports:
      - 80:2368
      - 2368:2368
    volumes:
      - ./src:/var/lib/ghost/content

  db:
    image: mariadb:10
    volumes:
      - ./data/:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: default_root_password
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost_user
      MYSQL_PASSWORD: ghost_password
