version: '3.1'

services:

  server:
    image: ghost:4.1
    depends_on:
      - db
    volumes:
      - ./src:/var/lib/ghost/content
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: password
      database__connection__database: ghost
      url: http://localhost

  db:
    image: mysql:8
    volumes:
      - ./data/:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
